### ISSUE TITLE
Question: How to generate default.min.css

### ISSUE THREAD

**Issue by flip3** [redaxmedia/redaxscript#454]
Hello,

No bug but a question: How can I generate the default.min.css file in the /templates/default/dist/styles folder so that my style changes actually become visible on the website?

Also, I made a copy of the default and wide theme, renamed them to ls-default & ls-wide and uploaded them to the templates directory. Then I chose them in the backend under System  Settings from the templates dropdown and saved. However my selection wasn’t saved and the templates dropdown remained empty. What else do I need to do when creating a template?

Many thanks,

Philip

**Comment by redaxmedia** [comment]
Hello,

we are currently in beta phase, unfortunately the old [wiki](https://github.com/redaxmedia/redaxscript/wiki) is not ported yet to the new [documentation](https://github.com/redaxmedia/redaxscript-documentation).

Redaxscript 3.0.0 is working with PostCSS, something similar to SASS or LESS but more like a framework rather than a language. However, you have to use the Grunt.js with the command "grunt build" to generate the JS, CSS and fonts or "grunt build-css" just for CSS.

You can find an old "Grunt guide" in the old wiki.

Please do not work on top of the default template and use the skeleton template instead. It is recommended to start from a clean template and pick only needed parts from the default template.

Another thing issue is the cache, if you change something in your template it still takes the CSS from cache/styles... you can delete the cache folder while development or you use the parameter ?nocache=true to disable it.

**Comment by redaxmedia** [comment]
Please reopen if you have further questions... we can chat on Gitter too.
