### ISSUE TITLE
Alias Problem in Georgian

### ISSUE THREAD

**Issue by vdanelia** [redaxmedia/redaxscript#485]
When creating / adding new articles or categories the Alias is not generated automatically like it does in English or in Russian languages..... (have to make it manually).
I remember that we implemented that in old version of the script :) 

Please re add that compability to a new version of the script.... woulg be perfect
Thanks! :)

**Comment by redaxmedia** [comment]
Hello my old friend, glad to see you again.

Someone requested support for the Arabian language. I watched the years old alias function and had to realize that I have to switch to a third party solution doing a better job.

For most languages like Russian the results were better than my solution. Unfortunately the third party library does not have all the languages that were supported before.

So I ask you to contribute to https://github.com/pid/speakingurl - I suggest to send a pull request because to issues does not help the author of the library as he does not speak your language.

Good luck and sorry for the extra round.

**Comment by vdanelia** [comment]
ok I'll check that project and will contribute ;)

**Comment by vdanelia** [comment]
:+1:
